#!/usr/bin/env python3
"""Enrich a progression-router plan into a guide-chain guide JSON.

Reads a plan (from plan.mjs) on stdin, enriches each step with render metadata,
and emits a guide-chain guide {id,name,description,steps[]} on stdout.

This is the keystone JOIN: router abstract plan (predicate reqs/grants) -> the
plugin's render schema (instruction prose + highlights/markers + auto-advance
completion conditions). Two mechanical pieces here:
  * topological ORDER — the greedy planner emits the step SET cost-first, not in
    prerequisite order, so we re-order by simulating skill state (a step is
    emittable once its skill reqs are met), yielding a valid play order.
  * grant -> completionCondition — reaching a granted skill level is the step's
    natural auto-advance (SKILL >= level).
Location -> map marker + a representative training-NPC highlight via catalog.json.
"""
import json
import sys
from pathlib import Path

SKILL_ENUM = {  # router skill key -> net.runelite.api.Skill enum constant
    "attack": "ATTACK", "strength": "STRENGTH", "defence": "DEFENCE", "ranged": "RANGED",
    "prayer": "PRAYER", "magic": "MAGIC", "runecraft": "RUNECRAFT", "construction": "CONSTRUCTION",
    "hitpoints": "HITPOINTS", "agility": "AGILITY", "herblore": "HERBLORE", "thieving": "THIEVING",
    "crafting": "CRAFTING", "fletching": "FLETCHING", "slayer": "SLAYER", "hunter": "HUNTER",
    "mining": "MINING", "smithing": "SMITHING", "fishing": "FISHING", "cooking": "COOKING",
    "firemaking": "FIREMAKING", "woodcutting": "WOODCUTTING", "farming": "FARMING",
}


def skill_cond(skill, level):
    return {"type": "SKILL", "skill": SKILL_ENUM.get(skill, skill.upper()), "level": int(level)}


def topo_order(steps):
    """Valid play order: emit a step once its skill reqs are met, applying grants."""
    state, remaining, ordered = {}, list(steps), []
    lvl = lambda k: state.get(k, 1)
    while remaining:
        progressed = False
        for s in list(remaining):
            reqs = (s.get("reqs") or {}).get("skills", {}) or {}
            if all(lvl(k) >= v for k, v in reqs.items()):
                ordered.append(s)
                for k, v in (s.get("grants") or {}).items():
                    if isinstance(v, (int, float)):
                        state[k] = max(lvl(k), v)
                remaining.remove(s)
                progressed = True
        if not progressed:               # unmet dep -> append remainder verbatim
            ordered.extend(remaining)
            break
    return ordered


def enrich(plan, catalog):
    goal = plan["goal"]
    zones = catalog.get("zones", {})
    reals = [s for s in plan["path"] if not s.get("_capstone")]
    capstone = next((s for s in plan["path"] if s.get("_capstone")), None)

    steps = []
    for s in topo_order(reals):
        conds = [skill_cond(k, v) for k, v in (s.get("grants") or {}).items() if k in SKILL_ENUM]
        cat = zones.get((s.get("location") or {}).get("zone"))
        steps.append({
            "id": s["id"],
            "instruction": s.get("label", s["id"]),
            "detail": s.get("detail", ""),
            "highlights": [{"type": "NPC", "id": cat["npc"]}] if cat and cat.get("npc") else [],
            "mapMarkers": [{"x": cat["x"], "y": cat["y"], "plane": cat.get("plane", 0),
                            "label": cat.get("label")}] if cat else [],
            "completionConditions": conds or [{"type": "MANUAL"}],
        })
    if capstone:
        reqs = (capstone.get("reqs") or {}).get("skills", {}) or {}
        steps.append({
            "id": capstone["id"],
            "instruction": f"You now meet the requirements for {goal['label']}.",
            "detail": "All prerequisite skills are trained — you can start this goal.",
            "highlights": [], "mapMarkers": [],
            "completionConditions": [skill_cond(k, v) for k, v in reqs.items()] or [{"type": "MANUAL"}],
        })

    gid = "route-" + goal["id"]
    return {
        "id": gid,
        "name": f"{goal['label']} — Requirements Route",
        "description": f"Optimised prerequisite route for {goal['label']}, "
                       "generated by the progression-router planner.",
        "steps": steps,
    }


def main():
    plan = json.load(sys.stdin)
    catalog = json.loads((Path(__file__).parent / "catalog.json").read_text())
    json.dump(enrich(plan, catalog), sys.stdout, indent=2)


if __name__ == "__main__":
    main()
